# source = /home/akshat/.cache/wal/colors-hyprland.conf

$foreground = "#ffffff"

# BACKGROUND
background {
    monitor =
    # path = screenshot
    path = /home/akshat/Pictures/Wallpapers/night-sky-stars-4k.jpeg
    # color = $background
    blur_passes = 2
    contrast = 1
    brightness = 0.4
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = false 
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    color = rgba(255, 0, 0, 1.0)
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgba(242, 243, 244, 0.75)
    fade_on_empty = false
    rounding = -1
    check_color = $foreground
    font_family = JetBrains Mono
    fail_color = rgba(200, 40, 40, 1.0)
    fail_text = <span>Authentication Failed</span>
    placeholder_text = <span foreground="##fff5">Input Password</span>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-H:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}



# Profile Picture
image {
    monitor =
    path = /home/akshat/Pictures/profile_pictures/profile-pic.jpeg
    size = 100
    border_size = 2
    border_color = $foreground
    position = 0, -100
    halign = center
    valign = center
}

# Desktop Environment
# image {
#     monitor =
#     path = /home/akshat/Pictures/profile_pictures/hypr.png
#     size = 75
#     border_size = 2
#     border_color = $foreground
#     position = -50, 50
#     halign = right
#     valign = bottom
# }

# CURRENT SONG
# label {
#     monitor =
#     text = cmd[update:1000] echo "$(/home//Documents/Scripts/whatsong.sh)" 
#     color = $foreground
#     #color = rgba(255, 255, 255, 0.6)
#     font_size = 18
#     font_family = Metropolis Light, Font Awesome 6 Free Solid
#     position = 0, 50
#     halign = center
#     valign = bottom
# }
#
# label {
#     monitor =
#     text = cmd[update:1000] echo "$(/home/akshat/Documents/Scripts/whoami.sh)"
#     color = $foreground
#     font_size = 14
#     font_family = JetBrains Mono
#     position = 0, -10
#     halign = center
#     valign = top
# }
#
# label {
#     monitor =
#     text = cmd[update:1000] echo "$(/home/justin/Documents/Scripts/network-status.sh)"
#     color = $foreground
#     font_size = 24
#     font_family = JetBrains Mono
#     position = -20, -10
#     halign = right
#     valign = top
# }
